ami = "ami-04706e771f950937f"
instance_type = "t2.micro"
key_name = "GitHubRunner"
github_repo_url = "https://github.com/RekhuGopal/GitHub-Action-OIDCConnect.git"
github_repo_pat_token = "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"
runner_name = "Surabhiterraform1234"
labels = "awsec2"
